Gorjanc/Controllers/OsebeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gorjanc.Data;
using Gorjanc.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Gorjanc.Controllers
{
    public class OsebeController : Controller
    {
        private readonly GorjancContext _context;

        public OsebeController(GorjancContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Obiskani(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oseba = await _context.Osebe
                .Include(o => o.Obiskani)
                    .ThenInclude(v => v.Vrh)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (oseba == null)
            {
                return NotFound();
            }

            return View(oseba);
        }

    }
}

Gorjanc/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Gorjanc.Models

@inject SignInManager<Oseba> SignInManager
@inject UserManager<Oseba> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gorjanc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/leaflet.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/leaflet.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-gpx/1.4.0/gpx.min.js"></script>
    <link href='https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css' rel='stylesheet' />
    <link href='https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css' rel='stylesheet' />
    <script src='https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js'></script>
    <link rel="icon" type="image/png" href="/Gorjanci150x150.png" />
</head>
<body onload="mapa()">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Vrhovi" asp-action="Index"><img src="~/favicon.ico" height="50vh"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vrhovi" asp-action="Index">Domov</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Vrhovi/#onas">O projektu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Vrhovi/#vrhovi">Vrhovi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Osebe" asp-action="Obiskani" asp-route-id="@UserManager.GetUserId(User)">Moji vrhovi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Žan Luka in Jan
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>